start on started lab126_gui
stop on stopping lab126_gui

script
    [ -f /mnt/us/token-on-kindle/background-enabled ] || exit 0
    exec /bin/sh /mnt/us/extensions/token-on-kindle/bin/scheduler.sh
end script
